### ISSUE TITLE
Get NoClassDefFoundError: org/slf4j/LoggerFactory running all.sh

### ISSUE THREAD

**Issue by gky99** [javalite/standalone-example#3]
```
 Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at org.javalite.activejdbc.DB.<clinit>(DB.java:46)
	at org.javalite.activejdbc.Base.open(Base.java:64)
	at activejdbc.examples.simple.SimpleExample.main(SimpleExample.java:10)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more
```

I simply run the code follow the instruction on my mac, but got those exceptions.

**Comment by ipolevoy** [comment]
@gky99 how do you run this code?

**Comment by ipolevoy** [comment]
@gky99 I see.  This is a bug in  this example since the logging changed a bit. I will fix it later.

**Comment by ipolevoy** [comment]
@gky99 wait... there is no bug. Just execute `all.sh`

**Comment by gky99** [comment]
@ipolevoy I did so. Just change the URL and password and run `all.sh`.
Actually, I got the same exception running the maven example too.

**Comment by gky99** [comment]
I'm working on macOS Sierra 10.12.3
MySQL version 5.7.17

**Comment by ipolevoy** [comment]
when I execute the `al.sh`, everything just works

```
➜  igor 15:28:30 /home/igor/projects/javalite/standalone-example git:(master) ./all.sh
**************************** START INSTRUMENTATION ****************************
Directory: classes
Instrumented class: /home/igor/projects/javalite/standalone-example/classes/activejdbc/examples/simple/Employee.class
**************************** END INSTRUMENTATION ****************************
161 [main] INFO activejdbc.examples.simple.SimpleExample - =========> Created employee:
167 [main] INFO activejdbc.examples.simple.SimpleExample - Model: activejdbc.examples.simple.Employee, table: 'employees', attributes: {first_name=John, id=5, last_name=Doe}
170 [main] INFO activejdbc.examples.simple.SimpleExample - =========> Updated employee:
171 [main] INFO activejdbc.examples.simple.SimpleExample - Employees list: [Model: activejdbc.examples.simple.Employee, table: 'employees', attributes: {first_name=John, id=5, last_name=Steinbeck}]
173 [main] INFO activejdbc.examples.simple.SimpleExample - =========> Deleted employee:
173 [main] INFO activejdbc.examples.simple.SimpleExample - Employees list: []
176 [main] INFO activejdbc.examples.simple.SimpleExample - =========> Created employee:
176 [main] INFO activejdbc.examples.simple.SimpleExample - Model: activejdbc.examples.simple.Employee, table: 'employees', attributes: {first_name=John, id=6, last_name=Doe}
178 [main] INFO activejdbc.examples.simple.SimpleExample - =========> Deleted all employees:
179 [main] INFO activejdbc.examples.simple.SimpleExample - Employees list: []
➜  igor 15:28:35 /home/igor/projects/javalite/standalone-example git:(master) 
```

Please, include your full output.

**Comment by gky99** [comment]
```guankaiyuedeMBP:standalone-example-master gky$ ./all.sh 
**************************** START INSTRUMENTATION ****************************
Directory: classes
Instrumented class: /Users/gky/Downloads/standalone-example-master/classes/activejdbc/examples/simple/Employee.class
**************************** END INSTRUMENTATION ****************************
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at org.javalite.activejdbc.DB.<clinit>(DB.java:46)
	at org.javalite.activejdbc.Base.open(Base.java:64)
	at activejdbc.examples.simple.SimpleExample.main(SimpleExample.java:10)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more
```

@ipolevoy Here is the full output.

**Comment by ipolevoy** [comment]
@gky99 did you make any changes to code or libraries?

**Comment by ipolevoy** [comment]
@gky99 I made a small fix. Pull new code and try again.

**Comment by gky99** [comment]
The new one produces exactly the same output as the old one.
I only changed the `Base.open()` and link it to my MySql database.

**Comment by ipolevoy** [comment]
@gky99 the script `run.sh` builds a classpath here using a Bash loop: https://github.com/javalite/standalone-example/blob/master/run.sh#L7. I think something wrong with that loop on your laptop. Can you try to modify that script to simply build the $CLASSPATH manually by adding jars from directory 'lib'? This is what the loop is doing. You cannot find `org.slf4j.LoggerFactory` but the SLF4J jar is sitting in the lib dir.

**Comment by gky99** [comment]
@ipolevoy I tried manually add all the `CLASSPATH` before running the script and delete all the `export` in the script. And still get the same output = =.

```
guankaiyuedeMacBook-Pro:standalone-example-master gky$ ./all.sh 
**************************** START INSTRUMENTATION ****************************
Directory: classes
Instrumented class: /Users/gky/Downloads/standalone-example-master/classes/activejdbc/examples/simple/Employee.class
**************************** END INSTRUMENTATION ****************************
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at org.javalite.activejdbc.DB.<clinit>(DB.java:46)
	at org.javalite.activejdbc.Base.open(Base.java:64)
	at activejdbc.examples.simple.SimpleExample.main(SimpleExample.java:10)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more

guankaiyuedeMacBook-Pro:standalone-example-master gky$ echo $CLASSPATH
/Users/gky/Downloads/standalone-example-master/build_time_libs/javassist-3.8.0.GA.jar:/Users/gky/Downloads/standalone-example-master/build_time_libs/activejdbc-instrumentation-1.4.11.jar:/Users/gky/Downloads/standalone-example-master/lib/slf4j-simple-1.5.10.jar:/Users/gky/Downloads/standalone-example-master/lib/slf4j-api-1.5.10.jar:/Users/gky/Downloads/standalone-example-master/lib/mysql-connector-java-5.0.4.jar:/Users/gky/Downloads/standalone-example-master/lib/javalite-common-1.4.11.jar:/Users/gky/Downloads/standalone-example-master/lib/activejdbc-1.4.11.jar:/Users/gky/Downloads/standalone-example-master/classes
```

And I find a problem that after running the original script, the `CLASSPATH` value stays unchanged. Is this behavior normal?

**Comment by ipolevoy** [comment]
@gky99 your script may not inherit the environment variable. Set the CLASSPATH inside the script. Alternatively, do not use script. Set CLASSPATH manually, then execute this command: 

`java -cp $CLASSPATH -DoutputDirectory=$OUTDIR activejdbc.examples.simple.SimpleExample`

**Comment by gky99** [comment]
@ipolevoy Still all the same...

```
guankaiyuedeMacBook-Pro:standalone-example-master gky$ java -cp $CLASSPATH -DoutputDirectory=$OUTDIR activejdbc.examples.simple.SimpleExample
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at org.javalite.activejdbc.DB.<clinit>(DB.java:46)
	at org.javalite.activejdbc.Base.open(Base.java:64)
	at activejdbc.examples.simple.SimpleExample.main(SimpleExample.java:10)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more
guankaiyuedeMacBook-Pro:standalone-example-master gky$ echo $CLASSPATH
/Users/gky/Downloads/standalone-example-master/build_time_libs/javassist-3.8.0.GA.jar:/Users/gky/Downloads/standalone-example-master/build_time_libs/activejdbc-instrumentation-1.4.11.jar:/Users/gky/Downloads/standalone-example-master/lib/slf4j-simple-1.5.10.jar:/Users/gky/Downloads/standalone-example-master/lib/slf4j-api-1.5.10.jar:/Users/gky/Downloads/standalone-example-master/lib/mysql-connector-java-5.0.4.jar:/Users/gky/Downloads/standalone-example-master/lib/javalite-common-1.4.11.jar:/Users/gky/Downloads/standalone-example-master/lib/activejdbc-1.4.11.jar:/Users/gky/Downloads/standalone-example-master/classes
```

**Comment by ipolevoy** [comment]
@gky99 for whatever reason, Java on your laptop is not finding the class `org.slf4j.LoggerFactory`. 

However, it is clearly inside the file `slf4j-api-1.5.10.jar`,  please see: 

```
➜  igor 8:16:12 /home/igor/projects/javalite/standalone-example/lib git:(master) jar tvf slf4j-api-1.5.10.jar
     0 Thu Dec 03 00:35:38 CST 2009 META-INF/
   558 Thu Dec 03 00:35:36 CST 2009 META-INF/MANIFEST.MF
     0 Thu Dec 03 00:33:00 CST 2009 org/
     0 Thu Dec 03 00:35:38 CST 2009 org/slf4j/
     0 Thu Dec 03 00:33:00 CST 2009 org/slf4j/helpers/
     0 Thu Dec 03 00:33:00 CST 2009 org/slf4j/spi/
  3366 Thu Dec 03 00:33:00 CST 2009 org/slf4j/helpers/BasicMarker.class
  1427 Thu Dec 03 00:33:00 CST 2009 org/slf4j/helpers/BasicMarkerFactory.class
  2071 Thu Dec 03 00:33:00 CST 2009 org/slf4j/helpers/BasicMDCAdapter.class
  4704 Thu Dec 03 00:33:00 CST 2009 org/slf4j/helpers/MarkerIgnoringBase.class
  6099 Thu Dec 03 00:33:00 CST 2009 org/slf4j/helpers/MessageFormatter.class
   823 Thu Dec 03 00:33:00 CST 2009 org/slf4j/helpers/NamedLoggerBase.class
  3267 Thu Dec 03 00:33:00 CST 2009 org/slf4j/helpers/NOPLogger.class
  1011 Thu Dec 03 00:33:00 CST 2009 org/slf4j/helpers/NOPMakerAdapter.class
   877 Thu Dec 03 00:33:00 CST 2009 org/slf4j/helpers/SubstituteLoggerFactory.class
   938 Thu Dec 03 00:33:00 CST 2009 org/slf4j/helpers/Util.class
   180 Thu Dec 03 00:33:00 CST 2009 org/slf4j/ILoggerFactory.class
   272 Thu Dec 03 00:33:00 CST 2009 org/slf4j/IMarkerFactory.class
  1375 Thu Dec 03 00:33:00 CST 2009 org/slf4j/Logger.class
  7119 Thu Dec 03 00:33:00 CST 2009 org/slf4j/LoggerFactory.class
   601 Thu Dec 03 00:33:00 CST 2009 org/slf4j/Marker.class
  1379 Thu Dec 03 00:33:00 CST 2009 org/slf4j/MarkerFactory.class
  2867 Thu Dec 03 00:33:00 CST 2009 org/slf4j/MDC.class
   436 Thu Dec 03 00:33:00 CST 2009 org/slf4j/spi/LocationAwareLogger.class
   249 Thu Dec 03 00:33:00 CST 2009 org/slf4j/spi/LoggerFactoryBinder.class
   249 Thu Dec 03 00:33:00 CST 2009 org/slf4j/spi/MarkerFactoryBinder.class
   384 Thu Dec 03 00:33:00 CST 2009 org/slf4j/spi/MDCAdapter.class
     0 Thu Dec 03 00:35:38 CST 2009 META-INF/maven/
     0 Thu Dec 03 00:35:38 CST 2009 META-INF/maven/org.slf4j/
     0 Thu Dec 03 00:35:38 CST 2009 META-INF/maven/org.slf4j/slf4j-api/
  2995 Thu Dec 03 00:04:20 CST 2009 META-INF/maven/org.slf4j/slf4j-api/pom.xml
   109 Thu Dec 03 00:33:00 CST 2009 META-INF/maven/org.slf4j/slf4j-api/pom.properties
```

Not sure why this is happening, but if you find the reason, you will run the example.

**Comment by gky99** [comment]
Yeah, surely I know it's because the class can't be found. I simply can't find any problem that may cause that. That's why I open that issue. I wonder if there is any possible problem in the command in run or build or instrument. Or if there is possibly some problem that may make the `LoggerFactory` class can't be load normally.

**Comment by ipolevoy** [comment]
@gky99  you can write a simple test in your class: 

    System.out.println(getClass().getResource("/org/slf4j/LoggerFactory.class"));

if this prints `null`, you do not have this class on classpath.

**Comment by VinsoyTisoy** [comment]
@ipolevoy  Is these error fixed? Im currently encountering this error too. All I did is establish a connection to my database. "Base.open(bla bla);"

**Comment by ipolevoy** [comment]
@VinsoyTisoy , I simply cannot reproduce it. Can  you provide more detail? Your operating system, how you execute the commands, your classpath, etc.

**Comment by VinsoyTisoy** [comment]
@ipolevoy I just downloaded the slf4j jar file and it went okay. I thought that the slf4j jar file is already in the ActiveJDBC jar file.

**Comment by RezaMasoudi** [comment]
this bug fixed?? I have this problem .. Caused by: java.lang.NoClassDefFoundError: org/javalite/activejdbc/Base !!!

**Comment by ipolevoy** [comment]
@RezaMasoudi  your exception is different than the one reported in this bug.
